["effects"."neon-bleed"."border"."outer"]
enabled = true
animated = true
speed = 1
padding = 14
passes = [{ shader = "../shaders/rings/neon-bleed.glsl" }]

["effects"."neon-bleed"."border"."inner"]
passes = [{ shader = "../shaders/window/neon-bleed-overlay.glsl" }]
