#!/usr/bin/env python3
"""Keep the paper border and inner overlay on exactly the same drawing clock."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "rings/scribbling-pencils.glsl").read_text()
header = """// Generated by tools/generate-paper-overlay.py; edit the ring source.
// Both hosts use logical client coordinates and the same compositor clock.
#define ring_size (umbriel_size / max(umbriel_scale, 0.01))

"""
footer = """
vec4 postprocess(vec3 coords) {
    vec4 source = tex2D_screen(coords.xy);
    vec2 p = coords.xy * ring_size;
    if (min(min(p.x, p.y), min(ring_size.x - p.x, ring_size.y - p.y)) > PENCIL_INSET)
        return source;
    vec4 pencil = ring_color(p);
    return vec4(source.rgb * (1.0 - pencil.a) + pencil.rgb * pencil.a * source.a, source.a);
}
"""
(ROOT / "window/scribbling-pencils-overlay.glsl").write_text(header + source + footer)
